version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: automerge_pro
      POSTGRES_USER: automerge
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./apps/backend
    environment:
      - DATABASE_URL=postgresql://automerge:password@postgres:5432/automerge_pro
      - REDIS_URL=redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./apps/backend:/app
      - /app/node_modules

  frontend:
    build: ./apps/frontend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data: