name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - MichaelWBrennan
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your needs.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's missing in the current functionality?
      placeholder: As a [user type], I need [functionality] so that [benefit/outcome]...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Auto-merge Rules & Logic
        - AI Risk Analysis & Security
        - Configuration & Setup
        - Dashboard & Analytics
        - Notifications & Integrations
        - API & Webhooks
        - CLI Tools & Developer Experience
        - Billing & Plans
        - Documentation
        - Performance & Reliability
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my usage)
        - High (Would significantly improve my workflow)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: dropdown
    id: plan
    attributes:
      label: Current Plan
      description: What plan are you currently using?
      options:
        - Free
        - Pro
        - Enterprise
        - Not a customer yet
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be helpful
      placeholder: |
        1. When I'm...
        2. In the case where...
        3. For teams that...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What workarounds or alternatives have you considered?
      placeholder: I've tried... but it doesn't work because...
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, share them here
      placeholder: This could work by... or maybe using...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature might work, including mock configurations or UI mockups
      render: yaml
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or screenshots about the feature request here
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this feature hasn't been requested already
          required: true
        - label: This feature would benefit other users, not just my specific use case
          required: true
        - label: I understand that feature requests are prioritized based on demand and feasibility
          required: true