name: Merge Orchestrator
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - name: Merge Dry Run
        run: node -e "require('fs').writeFileSync('merge-result.json', JSON.stringify({success:true, decisions:[]}))"
      - name: Post summary
        run: node scripts/post-merge-summary.js merge-result.json
